apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: sre
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: fluxautomation.azurecr.io/apps/nginx:1.23.4 #{"$imagepolicy":"default:nginxapp"}
        ports:
        - containerPort: 80
