---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dev-team
  namespace: dev
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: gitops-lab-deploy-auth
  url: ssh://github.com/peeyushgirdhar01/nginx
