---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sre-team
  namespace: sre
spec:
  interval: 1m0s
  path: ./code
  prune: false
  serviceAccountName: sre
  sourceRef:
    kind: GitRepository
    name: sre-team
